app/models.py
from datetime import datetime
from time import time
import re
# from app import app as app

from app import db

def slugify(s):
    pattern = r'[^\w+]'
    return re.sub(pattern, '-', s)


class Post(db.Model):
    id = db.Column(db.Integer,primary_key=True)
    title = db.Column(db.String(140))
    slug = db.Column(db.String(140), unique=True)
    body = db.Column(db.Text)
    created = db.Column(db.DateTime, default=datetime.now())

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.generate_slug()

    def generate_slug(self):
        if self.title:
            self.slug = slugify(self.title)
        else:
            self.slug = str(int(time()))

    def __repr__(self):
        return f'<Post id: {self.id}, title:{self.title}>'
    

app/app.py
from flask import Flask
from flask_sqlalchemy import SQLAlchemy



from config import Config
from posts.blueprint import posts

app = Flask(__name__)
app.config.from_object(Config)


app.register_blueprint(posts, url_prefix='/blog')

db = SQLAlchemy(app)

app/main.py
from app import app
from app import db
import views



if __name__ == '__main__':
    app.run()

app/posts/blueprint.py
from flask import Blueprint
from flask import render_template

from models import Post

posts = Blueprint('posts', __name__, template_folder='templates')

# localhost:5000/blog/
@posts.route('/')
def posts_list():
    return render_template('posts/posts.html', posts=posts)

@posts.route('/<slug>')
def post_detail(slug):
    post = Post.query.filter(Post.slug==slug).first()
    return render_template('post/post_detail.html', post=post)

app/views.py
from flask import render_template

from app import app


@app.route('/')
def index():
    animal = 'Tiger'
    return render_template('index.html', name=animal)

app/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <title>
        {% block title %}

        {% endblock %}
    </title>
</head>
<body>
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark mb-5">
            <a class="navbar-brand" href="{{ url_for('index') }}">Flask</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
            </button>
        
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                <a class="nav-link" href="{{ url_for('posts.posts_list') }}">Blog <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item">
                <a class="nav-link" href="#">Link</a>
                </li>
            </ul>
            <form class="form-inline my-2 my-lg-0">
                <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
                <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
            </form>
            </div>
        </nav>
        
        <div class="container">
            <div class="row">
                <div class="col-8 mx-auto">
                    {% block content  %}

                    {% endblock %}
                </div>
            </div>
        </div>
</body>
</html>

app/templates/index.html
{% extends 'base.html' %}


{% block title %}
    Index Page
{% endblock %}


{% block content %}
    <h1>Hello from Index.html</h1>
{% endblock %}